In [2]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
completions = pd.read_csv('compl.csv', encoding='utf8')

In [9]:
completions

,UserID,CourseID,CompletionDate,ContentType,Provider
0,278909,3718,4102020,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy
1,278909,6428,4152020,Getting Started with Agile,Techademy
2,281475,3718,4152020,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy
3,281475,7546,4192020,Learn SQL and Database Testing from Scratch+ U...,Techademy
4,283078,7808,4162020,Effective Jenkins: Continuous Delivery with Je...,Techademy
...,...,...,...,...,...
34465,10644499,830,10212020,Hands-On PySpark for Big Data Analysis,Techademy
34466,10645940,1980,10212020,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy
34467,10647872,1980,10212020,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy
34468,10668270,765,10152020,Java for beginners: Step-by-step hands-on guid...,Techademy
34469,10671580,20368,10212020,Mastering Docker (2017) the DevOps way by Scho...,Techademy

In [10]:
completions.count()

UserID            34470
CourseID          34470
CompletionDate    34470
ContentType       34470
Provider          34470
dtype: int64

In [11]:
ytd = pd.read_csv('ytd_report.csv')

In [12]:
ytd

,UserID,ContentType,ContentProvider,DateAdded,CompletionDate,ContentID
0,10663969,Complete Step By Step Java For Testers,Techademy,9/10/20,NaN,rxjloak
1,10609296,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/9/20,NaN,rxjwnd5
2,10647597,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/10/20,NaN,rxjwnd5
3,10652995,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/10/20,NaN,rxjwnd5
4,10647112,Complete Step By Step Java For Testers,Techademy,9/10/20,NaN,rxjloak
...,...,...,...,...,...,...
46925,10669503,Modern Python Solutions Part 1,Techademy,9/10/20,1/6/20,rxjwAv3
46926,10668611,Modern Python Solutions Part 1,Techademy,9/10/20,1/6/20,rxjwAv3
46927,10659889,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/10/20,1/6/20,rxjwnd5
46928,10082667,Getting Started with Angular,Techademy,9/10/20,1/6/20,rxjAZL4
46929,10669251,Complete Step By Step Java For Testers,Techademy,9/10/20,1/5/20,rxjloak

In [255]:
completions

,UserID,CourseID,CompletionDate,ContentType,Provider
0,278909,3718,4102020,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy
1,278909,6428,4152020,Getting Started with Agile,Techademy
2,281475,3718,4152020,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy
3,281475,7546,4192020,Learn SQL and Database Testing from Scratch+ U...,Techademy
4,283078,7808,4162020,Effective Jenkins: Continuous Delivery with Je...,Techademy
...,...,...,...,...,...
34465,10644499,830,10212020,Hands-On PySpark for Big Data Analysis,Techademy
34466,10645940,1980,10212020,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy
34467,10647872,1980,10212020,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy
34468,10668270,765,10152020,Java for beginners: Step-by-step hands-on guid...,Techademy
34469,10671580,20368,10212020,Mastering Docker (2017) the DevOps way by Scho...,Techademy

In [256]:
completions['ContentTypeLower'] = completions['ContentType'].str.lower()

In [257]:
completions

,UserID,CourseID,CompletionDate,ContentType,Provider,ContentTypeLower
0,278909,3718,4102020,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy,agile scrum course: scrum fundamentals -scrum ...
1,278909,6428,4152020,Getting Started with Agile,Techademy,getting started with agile
2,281475,3718,4152020,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy,agile scrum course: scrum fundamentals -scrum ...
3,281475,7546,4192020,Learn SQL and Database Testing from Scratch+ U...,Techademy,learn sql and database testing from scratch+ u...
4,283078,7808,4162020,Effective Jenkins: Continuous Delivery with Je...,Techademy,effective jenkins: continuous delivery with je...
...,...,...,...,...,...,...
34465,10644499,830,10212020,Hands-On PySpark for Big Data Analysis,Techademy,hands-on pyspark for big data analysis
34466,10645940,1980,10212020,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy,itil® 4 foundation complete course with 2 prac...
34467,10647872,1980,10212020,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy,itil® 4 foundation complete course with 2 prac...
34468,10668270,765,10152020,Java for beginners: Step-by-step hands-on guid...,Techademy,java for beginners: step-by-step hands-on guid...
34469,10671580,20368,10212020,Mastering Docker (2017) the DevOps way by Scho...,Techademy,mastering docker (2017) the devops way by scho...

In [193]:
ytd['ContentTypeLower'] = ytd['ContentType'].str.lower()

In [194]:
ytd

,UserID,ContentType,ContentProvider,DateAdded,CompletionDate,ContentID,ContentTypeLower
0,10663969,Complete Step By Step Java For Testers,Techademy,9/10/20,NaN,rxjloak,complete step by step java for testers
1,10609296,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/9/20,NaN,rxjwnd5,az-900 microsoft azure fundamentals 2020
2,10647597,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/10/20,NaN,rxjwnd5,az-900 microsoft azure fundamentals 2020
3,10652995,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/10/20,NaN,rxjwnd5,az-900 microsoft azure fundamentals 2020
4,10647112,Complete Step By Step Java For Testers,Techademy,9/10/20,NaN,rxjloak,complete step by step java for testers
...,...,...,...,...,...,...,...
46925,10669503,Modern Python Solutions Part 1,Techademy,9/10/20,1/6/20,rxjwAv3,modern python solutions part 1
46926,10668611,Modern Python Solutions Part 1,Techademy,9/10/20,1/6/20,rxjwAv3,modern python solutions part 1
46927,10659889,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,9/10/20,1/6/20,rxjwnd5,az-900 microsoft azure fundamentals 2020
46928,10082667,Getting Started with Angular,Techademy,9/10/20,1/6/20,rxjAZL4,getting started with angular
46929,10669251,Complete Step By Step Java For Testers,Techademy,9/10/20,1/5/20,rxjloak,complete step by step java for testers

In [258]:
matched_records = completions.merge(ytd, how='outer', on=['UserID', 'ContentTypeLower'], indicator="source")

In [259]:
matched_records

,UserID,CourseID,CompletionDate_x,ContentType_x,Provider,ContentTypeLower,ContentType_y,ContentProvider,DateAdded,CompletionDate_y,ContentID,source
0,278909,3718.0,4102020.0,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy,agile scrum course: scrum fundamentals -scrum ...,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy,9/10/20,4/10/20,rx72eA9,both
1,278909,6428.0,4152020.0,Getting Started with Agile,Techademy,getting started with agile,Getting Started with Agile,Techademy,9/10/20,4/15/20,rxjA2d0,both
2,281475,3718.0,4152020.0,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy,agile scrum course: scrum fundamentals -scrum ...,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy,9/10/20,4/15/20,rx72eA9,both
3,281475,7546.0,4192020.0,Learn SQL and Database Testing from Scratch+ U...,Techademy,learn sql and database testing from scratch+ u...,Learn SQL and Database Testing from Scratch+ U...,Techademy,9/10/20,4/19/20,rxjA3pR,both
4,283078,7808.0,4162020.0,Effective Jenkins: Continuous Delivery with Je...,Techademy,effective jenkins: continuous delivery with je...,Effective Jenkins: Continuous Delivery with Je...,Techademy,9/10/20,4/16/20,rxjAep9,both
...,...,...,...,...,...,...,...,...,...,...,...,...
49160,10647389,NaN,NaN,NaN,NaN,complete step by step java for testers,Complete Step By Step Java For Testers,Techademy,9/10/20,1/6/20,rxjloak,right_only
49161,10669503,NaN,NaN,NaN,NaN,modern python solutions part 1,Modern Python Solutions Part 1,Techademy,9/10/20,1/6/20,rxjwAv3,right_only
49162,10668611,NaN,NaN,NaN,NaN,modern python solutions part 1,Modern Python Solutions Part 1,Techademy,9/10/20,1/6/20,rxjwAv3,right_only
49163,10082667,NaN,NaN,NaN,NaN,getting started with angular,Getting Started with Angular,Techademy,9/10/20,1/6/20,rxjAZL4,right_only
49164,10669251,NaN,NaN,NaN,NaN,complete step by step java for testers,Complete Step By Step Java For Testers,Techademy,9/10/20,1/5/20,rxjloak,right_only

In [260]:
matched_records.source.value_counts()

both          32241
right_only    14695
left_only      2229
Name: source, dtype: int64

In [261]:
result = matched_records[matched_records.source.eq('left_only')].drop('source', axis=1)

In [262]:
result

,UserID,CourseID,CompletionDate_x,ContentType_x,Provider,ContentTypeLower,ContentType_y,ContentProvider,DateAdded,CompletionDate_y,ContentID
108,10630036,6358.0,4172020.0,Advanced Linux System Administration,Techademy,advanced linux system administration,NaN,NaN,NaN,NaN,NaN
225,10644679,6923.0,4082020.0,An Introduction to Bootstrap 4,Techademy,an introduction to bootstrap 4,NaN,NaN,NaN,NaN,NaN
338,10652355,3718.0,4172020.0,Agile Scrum Course: Scrum Fundamentals -Scrum ...,Techademy,agile scrum course: scrum fundamentals -scrum ...,NaN,NaN,NaN,NaN,NaN
367,10653447,7752.0,4152020.0,Enterprise Automation with Python,Techademy,enterprise automation with python,NaN,NaN,NaN,NaN,NaN
368,10653447,7827.0,4152020.0,Machine learning for absolute beginners,Techademy,machine learning for absolute beginners,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
34460,10660412,3850.0,10202020.0,AZ-900 Microsoft Azure Fundamentals 2020,Techademy,az-900 microsoft azure fundamentals 2020,NaN,NaN,NaN,NaN,NaN
34462,10669384,1980.0,10202020.0,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy,itil® 4 foundation complete course with 2 prac...,NaN,NaN,NaN,NaN,NaN
34466,10645940,1980.0,10212020.0,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy,itil® 4 foundation complete course with 2 prac...,NaN,NaN,NaN,NaN,NaN
34467,10647872,1980.0,10212020.0,ITIL® 4 Foundation Complete Course with 2 Prac...,Techademy,itil® 4 foundation complete course with 2 prac...,NaN,NaN,NaN,NaN,NaN
34469,10671580,20368.0,10212020.0,Mastering Docker (2017) the DevOps way by Scho...,Techademy,mastering docker (2017) the devops way by scho...,NaN,NaN,NaN,NaN,NaN

In [268]:
result.to_csv('records_not_found.csv')

In [265]:
ytd.loc[ytd['UserID'] == 10644679]

Empty DataFrame
Columns: [UserID, ContentType, ContentProvider, DateAdded, CompletionDate, ContentID, ContentTypeLower]
Index: []

In [266]:
completions.loc[completions['UserID'] == 10644679]

,UserID,CourseID,CompletionDate,ContentType,Provider,ContentTypeLower
225,10644679,6923,4082020,An Introduction to Bootstrap 4,Techademy,an introduction to bootstrap 4
2386,10644679,6153,5012020,Beginning JavaScript jQuery,Techademy,beginning javascript jquery
2387,10644679,6865,5022020,What's New in Java 8: Lambdas,Techademy,what's new in java 8: lambdas
2388,10644679,6868,5022020,Spring MVC For Beginners : Build a Java Web Ap...,Techademy,spring mvc for beginners : build a java web ap...
2389,10644679,5943,5022020,"Building Web Apps with jQuery,JavaScript and B...",Techademy,"building web apps with jquery,javascript and b..."
2390,10644679,6205,5022020,Spring framework for beginners,Techademy,spring framework for beginners
2391,10644679,6179,5022020,Building Microservices from Scratch,Techademy,building microservices from scratch
2392,10644679,6122,5022020,Building Web Services with Java EE 8,Techademy,building web services with java ee 8
2393,10644679,6118,5022020,Java EE 8 Microservices,Techademy,java ee 8 microservices
2394,10644679,7073,5022020,Hands-On Microservices with Spring Boot 2.0,Techademy,hands-on microservices with spring boot 2.0
2395,10644679,7804,5022020,Java EE 8 Application Development,Techademy,java ee 8 application development
2396,10644679,630,5022020,Learning Java 9 - Databases and Multithreading...,Techademy,learning java 9 - databases and multithreading...
2397,10644679,632,5022020,Learning Java 9 - Modular Programming,Techademy,learning java 9 - modular programming
2398,10644679,633,5022020,Learning Java 9 - Object Oriented Programming,Techademy,learning java 9 - object oriented programming
2399,10644679,6218,5062020,Learning Spring Boot,Techademy,learning spring boot
2400,10644679,6257,5062020,Getting Started with Spring 5.0,Techademy,getting started with spring 5.0
2401,10644679,7443,5062020,Getting Started with Spring Boot 2.0,Techademy,getting started with spring boot 2.0

In [13]:
ytd.ContentType.unique()

array(['Complete Step By Step Java For Testers',
       'AZ-900 Microsoft Azure Fundamentals 2020',
       'Modern Python Solutions Part 1', ...,
       'Python for Finance: Investment Fundamentals and Data Analytics',
       'Mastering Redux', 'Getting started with Shiny'], dtype=object)

In [26]:
ytd_content = pd.ytd.ContentType.unique()

AttributeError: module 'pandas' has no attribute 'ytd'

In [24]:
ytd_content

array(['Complete Step By Step Java For Testers',
       'AZ-900 Microsoft Azure Fundamentals 2020',
       'Modern Python Solutions Part 1', ...,
       'Python for Finance: Investment Fundamentals and Data Analytics',
       'Mastering Redux', 'Getting started with Shiny'], dtype=object)

In [19]:
ytd.UserID.unique()

array([10663969, 10609296, 10647597, ..., 10656829, 10621004, 10651261])

In [20]:
ytd_content

array(['Complete Step By Step Java For Testers',
       'AZ-900 Microsoft Azure Fundamentals 2020',
       'Modern Python Solutions Part 1', ...,
       'Python for Finance: Investment Fundamentals and Data Analytics',
       'Mastering Redux', 'Getting started with Shiny'], dtype=object)

In [28]:
ytd.nunique()

UserID             8765
ContentType        1507
ContentProvider       1
DateAdded            16
CompletionDate      230
ContentID          1509
dtype: int64

In [31]:
content = pd.DataFrame(ytd_content)

In [32]:
content

                                                      0
0                Complete Step By Step Java For Testers
1              AZ-900 Microsoft Azure Fundamentals 2020
2                        Modern Python Solutions Part 1
3     The Fundamentals of User Experience - a Proces...
4                              Learning Microsoft Azure
...                                                 ...
1502                                     Learning Flask
1503                      Fundamentals of UX Techniques
1504  Python for Finance: Investment Fundamentals an...
1505                                    Mastering Redux
1506                         Getting started with Shiny

[1507 rows x 1 columns]

In [33]:
content.to_csv('unique_content.csv')